name: SmartSpawner
version: 1.0
main: me.siam.spawner.SpawnerPlugin
api-version: 1.21
depend: [Vault]

commands:
  spawner:
    description: Main spawner command
    usage: /spawner
    permission: spawner.use

permissions:
  spawner.use:
    default: true
